name: UI Web Automation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Jalankan UI Test
        run: ./gradlew test

      - name: Upload hasil pengujian
        uses: actions/upload-artifact@v4
        with:
          name: laporan-pengujian
          path: target/cucumber-reports.html  # Sesuaikan path sesuai dengan lokasi hasil pengujian di proyek Anda
